### ISSUE TITLE
After upgrade to 0.9.14 (TS 3.6.3), build fails

### ISSUE THREAD

**Issue by perbergland** [Adornis/typescript#19]
I'm sure I'm doing something stupid.

I just ran meteor update to get 

```
adornis:typescript@0.9.14
adornis:typescript-compiler@0.12.14
```

and now when I try to build, I get

```
meteor run --inspect=9229 --settings .deploy/settings.json
[[[[[ ~/Projects/refapp/refapp ]]]]]          

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While loading plugin `typescript` from package `adornis:typescript`:
   module.js:548:15: Cannot find module
   '/Users/me/.meteor/packages/meteor-tool/.1.8.1.znys04.feif++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@babel/runtime/helpers/objectSpread2'
   at Function.Module._resolveFilename (module.js:548:15)
   at Function.Module._load (module.js:475:25)
   at Module.require (module.js:597:17)
   at require (internal/module.js:11:18)
   at Object.require (/tools/isobuild/bundler.js:2126:22)
   at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
   at Module.require (packages/modules-runtime.js:244:14)
   at Module.moduleLink
   (/Users/me/.meteor/packages/adornis_typescript/.0.9.14.1bhny57.b98rk++os+web.browser+web.browser.legacy+web.cordova/plugin.typescript.os/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
   at packages/adornis:typescript-compiler/meteor-typescript/index.js:1:27
   at index.js (packages/adornis:typescript-compiler/meteor-typescript/index.js:290:1)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at packages/adornis:typescript-compiler/typescript-compiler.js:1:57
   at typescript-compiler.js (packages/adornis:typescript-compiler/typescript-compiler.js:32:1)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at <runJavaScript-54>:2896:1
   at <runJavaScript-54>:2906:3
```

I've tried adding typescript 3.6.3 manually to my project and I also installed it globally using npm -g but none of that helped.

**Comment by yorrd** [comment]
thanks for reporting. It seems to work for me at first glance. Didnt do heavier investigation. 

However, I highly suggest you having a look at the beta typescript package from meteor. Benjamn just released a somewhat official prerelease version a couple of weeks back which works really well and doesn't do as much recompilation on file change because it basically just ignores its dependencies, trusting they are compiled well. We ourselves are switching to that package in the coming weeks. I'll add an official deprecation notice as soon as the meteor package is released fully

**Comment by perbergland** [comment]
Alright thanks for the info - I read the info on 1.8.2 but it wasn't clear if the typescript support was experimental or not and how configurable it was.

**Comment by afrokick** [comment]
I have the same error

**Comment by afrokick** [comment]
@perbergland I fixed the issue with `meteor npm i @babel/helpers`

**Comment by perbergland** [comment]
I upgraded both helpers and runtime and it did not help :)

    "@babel/helpers": "^7.7.0",
    "@babel/runtime": "^7.7.2",

I also tried upgrading to 1.8.2 and get the same error.
Also trie `meteor remove adornis:typescript ` and then it seems that my typescript files don't even compile so something is wrong…

**Comment by afrokick** [comment]
because you need to install official meteor's typescript instead of adornis.

`meteor add typescript`

**Comment by perbergland** [comment]
After *actually* upgrading to 1.8.2 I can now at least use this package.

I tried the "official" package and I didn't like it much:

* It didn't produce any type errors on the console when I introduced some in the .ts code. Or did I do something wrong? There is no progress at all from the ts compilation from what I could see.
* There doesn't seem to be any way to configure typescript (e.g. strictNullChecks) as per the release notes (no parsing of tsconfig.json).

Maybe we should keep this package until the official supported package is at v2?

**Comment by perbergland** [comment]
OK, building now works but at runtime (with Meteor 1.8.2 and adornis:typescript@0.9.14) I get the following error:

```
.../.meteor/packages/promise/.0.11.2.hy69oz.ytuae++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20191115-13:18:23.853(1)? (STDERR)       throw error;
W20191115-13:18:23.854(1)? (STDERR)       ^
W20191115-13:18:23.854(1)? (STDERR) 
W20191115-13:18:23.854(1)? (STDERR) ReferenceError: __spreadArrays is not defined
```

for code that uses an array spread.

That seems to be a separate error… Maybe I should just close this issue and report the new one
